### ISSUE TITLE
sweet.js/helpers not installed

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet-cli#2]
I know it's just one file, but should we make a repo for `helpers`? We could have `sweet-cli` depend on it.

Another option, would be to put the helpers into the environment :nauseated_face:

**Comment by disnet** [comment]
Ha, I didn't see this issue until just now. Apparently Github doesn't automatically have you watch repos you create.

Anyway, yeah sweet-helpers is a repo now.
